accounts/urls.py
from django.urls import path,re_path
from .views import SearchView

app_name='accounts'

urlpatterns=[
    path('search/',SearchView.as_view(),name='search')
]

chats/urls.py
from django.urls import path,re_path
from .views import create_personal_room
app_name='chats'
 
urlpatterns=[
    path('ChatRoom/<int:pk>',create_personal_room,name='create_personal_room'),
    # re_path(r'^PersonalChatRoom/$',show_personal_chat_room,name='personal_chat_room'),
]

django_chat/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from .views import home_chat_view,group_chat_view
from allauth.account.views import LoginView
login = LoginView.as_view()

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^home_chat/$',home_chat_view,name='home'),    
    re_path(r'^home_groups/$',group_chat_view,name='home_groups'),    
    path("", login, name="account_login"),
    path('accounts/', include('allauth.urls')),
    path('accounts_/', include('accounts.urls')),
    path('chats/', include('chats.urls')),
    re_path('groups/', include('groups.urls')),
]

templates/snippets/search_form.html
<form class="ms-3 me-3" action='{% url 'accounts:search' %}' method='get' role="search">
    <input class="form-control bg-transparent searchinput" name='q' value="{{request.GET.q}}" type="search" placeholder="Search" aria-label="Search">
    <i class="bi bi-search me-5 mt-1" id='searchicon'></i>
    <script>
      $(document).ready(function(){
        $('.searchinput').hide();
        $('#searchicon').click(function(){
          $('#searchicon').hide()
          $('.searchinput').show();
          $('.searchinput').focus()
        })
        $('.searchinput').focusout(function(){
          $('#searchicon').show()
          $('.searchinput').hide();
        })
      })
    </script>
  </form> 

templates/snippets/search_view.html
{% extends 'base.html' %}
{% block content %}
    <div class="card MainContent mt-2" style="width: 100%;">
    {% for i in qs %}
    <a href="{% url 'chats:create_personal_room' pk=i.id %}" class='btn p-0'>
    <div class="card-header bg-secondary">           
      {{i}}
      </div>
    </a>
      {% comment %} <script>
        $('document').ready(function(){
            var user=$('#{{i.id}}')
            user.click(function(event){
                event.preventDefault()
                data={
                    'id':`{{i.id}}`
                }
                $.ajax({
                    url:`{% url 'chats:create_personal_room' %}`,
                    method: 'GET',
                    data:data,
                    success:function(response){
                        console.log(response)
                    },
                    error:function(errorData){
                        console.log(errorData)
                    }
                })
            })
        });
    </script> {% endcomment %}
      <ul class="list-group list-group-flush bg-success border-bottom border-5">
        <li class="ms-2 list-group-item mb-2"><span id="{{i.reciever}}chatbox"></span> .....</li>        
      </ul>
      {% empty %}      
      <div class="card-header bg-secondary">
      </div>
      <ul class="list-group list-group-flush bg-success border-bottom border-5">
        <li class="ms-2 list-group-item mb-2">No User Found!!</span></li>        
      </ul>
    {% endfor %}
</div>
{% endblock content %}