chats/urls.py
from django.urls import path,re_path
from .views import create_personal_room
app_name='chats'
 
urlpatterns=[
    path('ChatRoom/<int:pk>',create_personal_room,name='create_personal_room'),
    # re_path(r'^PersonalChatRoom/$',show_personal_chat_room,name='personal_chat_room'),
]

django_chat/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from .views import home_chat_view,group_chat_view
from allauth.account.views import LoginView
login = LoginView.as_view()

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^home_chat/$',home_chat_view,name='home'),    
    re_path(r'^home_groups/$',group_chat_view,name='home_groups'),    
    path("", login, name="account_login"),
    path('accounts/', include('allauth.urls')),
    path('accounts_/', include('accounts.urls')),
    path('chats/', include('chats.urls')),
    re_path('groups/', include('groups.urls')),
]

groups/urls.py
from django.urls import path,re_path
from .views import group_chat_room

app_name='groups'

urlpatterns=[
    path('GroupChatRoom/<int:pk>/',group_chat_room,name='group_chat_room')
    ]

chats/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError  
from django.dispatch import receiver
from django.db.models.signals import post_save,m2m_changed

# Create your models here.

class PersonalChatManager(models.Manager):
    def get_personal_chats(self,request,user):
        user=request.user
        chat_objects=self.get_queryset().filter(sender=user).values('reciever').distinct()
        qs={}
        for i in chat_objects:
            qs.update({f'object {i["reciever"]}':PersonalChat.objects.filter(reciever=i['reciever']).all().last()})    
        return qs

class PersonalChat(models.Model):
    chat=models.CharField(max_length=500,null=False,blank=False)
    sender=models.ForeignKey(User,on_delete=models.CASCADE,related_name='sender')
    reciever=models.ForeignKey(User,related_name='reciever',on_delete=models.CASCADE,null=False,blank=False)
    timestamp=models.DateTimeField(auto_now_add=True)   
    viewed_by=models.ManyToManyField(User,null=True,blank=True)
    
    def __str__(self):
        return f'{self.chat}'
    
    objects=PersonalChatManager()
    
@receiver(post_save,sender=PersonalChat)
def add_chat_to_chat_room(sender,instance,created,*args,**kwargs):
    if created:
        sender_=instance.sender
        reciever=instance.reciever
        chat_roomobj=PersonalChatRoom.objects.all()
        for i in chat_roomobj:
            if sender_ in i.members.all() and reciever in i.members.all():
                new_obj=i
                i.chats.add(instance)
            else:
                pass
        
        
class PersonalChatRoomManager(models.Manager):
    def new_or_get(self,request,chat_partner):
        current_user=request.user
        chat_partner=chat_partner
        chat_roomobj=PersonalChatRoom.objects.all()
        if chat_roomobj:        
            for i in chat_roomobj:
                if current_user in i.members.all() and chat_partner in i.members.all():
                    room_obj=i
                    print(room_obj)
                    return room_obj
            room_obj=PersonalChatRoom.objects.create()        
            room_obj.members.add(current_user)
            room_obj.members.add(chat_partner)
            return room_obj
        else:
            room_obj=PersonalChatRoom.objects.create()        
            room_obj.members.add(current_user)
            room_obj.members.add(chat_partner)
            return room_obj
        
    
class PersonalChatRoom(models.Model):    
    RoomName=models.CharField(max_length=255,blank=True,null=True)
    members=models.ManyToManyField(User,related_name='members')
    chats=models.ManyToManyField(PersonalChat,null=True,blank=True)
    timestamp=models.DateTimeField(auto_now_add=True)
    last_updated=models.DateTimeField(null=True, blank=True)
    members_online=models.ManyToManyField(User,blank=True,null=True,related_name='online_members')
    
    objects=PersonalChatRoomManager()
    
@receiver(m2m_changed,sender=PersonalChatRoom.members.through)
def post_save_room(instance,sender,action,*args,**kwargs):
        print('created')    
        room_name=''
        print(instance.members.all())
        users=instance.members.all()
        for i in users:
            room_name+=i.username
        print(room_name)
        instance.RoomName=room_name
        instance.save()
    

            
    
    

groups/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError  
from django.dispatch import receiver
from django.db.models.signals import post_save,m2m_changed

# Create your models here.


class GroupChat(models.Model):
    chat=models.CharField(max_length=500,null=False,blank=False)
    sender=models.ForeignKey(User,on_delete=models.CASCADE,related_name='GroupSender')
    reciever=models.ManyToManyField(User,related_name='Groupreciever',null=False,blank=False)
    timestamp=models.DateTimeField(auto_now_add=True)   
    viewed_by=models.ManyToManyField(User,null=True,blank=True,related_name='GroupViewedBy')
    
    def __str__(self):
        return f'{self.chat}'
    
# @receiver(post_save,sender=PersonalChat)
# def add_chat_to_chat_room(sender,instance,created,*args,**kwargs):
#     if created:
#         sender_=instance.sender
#         reciever=instance.reciever
#         chat_roomobj=PersonalChatRoom.objects.all()
#         for i in chat_roomobj:
#             if sender_ in i.members.all() and reciever in i.members.all():
#                 new_obj=i
#                 i.chats.add(instance)
#             else:
#                 pass
        
        
# class ChatRoomManager(models.Manager):
#     def new_or_get(self,request,chat_partner):
#         current_user=request.user
#         chat_partner=chat_partner
#         chat_roomobj=PersonalChatRoom.objects.all()
#         if chat_roomobj:        
#             for i in chat_roomobj:
#                 if current_user in i.members.all() and chat_partner in i.members.all():
#                     room_obj=i
#                     print(room_obj)
#                     return room_obj
#             room_obj=PersonalChatRoom.objects.create()        
#             room_obj.members.add(current_user)
#             room_obj.members.add(chat_partner)
#             return room_obj
#         else:
#             room_obj=PersonalChatRoom.objects.create()        
#             room_obj.members.add(current_user)
#             room_obj.members.add(chat_partner)
#             return room_obj
        
    
class GroupChatRoom(models.Model):    
    RoomName=models.CharField(max_length=255)
    members=models.ManyToManyField(User,related_name='groupmembers')
    chats=models.ManyToManyField(GroupChat,null=True,blank=True,related_name='GroupChats')
    timestamp=models.DateTimeField(auto_now_add=True)
    last_updated=models.DateTimeField(null=True, blank=True)
    members_online=models.ManyToManyField(User,blank=True,null=True,related_name='group_online_members')
    
    # objects=PersonalChatRoomManager()
    
# @receiver(m2m_changed,sender=PersonalChatRoom.members.through)
# def post_save_room(instance,sender,action,*args,**kwargs):
#         print('created')    
#         room_name=''
#         print(instance.members.all())
#         users=instance.members.all()
#         for i in users:
#             room_name+=i.username
#         print(room_name)
#         instance.RoomName=room_name
#         instance.save()
    

            
    
    

groups/forms.py
from .models import GroupChatRoom
from django import forms

class NewGroupForm(forms.ModelForm):
    class Meta:
        model=GroupChatRoom
        fields=('RoomName','members')
    

chats/views.py
from django.shortcuts import render
from .models import PersonalChatRoom
from django.http import JsonResponse,HttpResponse
import string
from django.shortcuts import redirect
from django.urls import reverse
import random
from django.contrib.auth.models import User
# Create your views here.

def create_personal_room(request,pk):
    user_id=pk
    current_user=request.user
    chat_partner=User.objects.get(id=user_id)   
    RoomObject=PersonalChatRoom.objects.new_or_get(request,chat_partner)
    for i in RoomObject.chats.all():
        i.viewed_by.add(current_user)
    context={
        'chat_partner':chat_partner,
        'RoomObject':RoomObject,
        
    }
    return render(request,'chats/personal_chat_room.html',context)
    

groups/views.py
from django.shortcuts import render
from .models import GroupChatRoom
import json


# Create your views here.

def group_chat_room(request,pk):
    qs=GroupChatRoom.objects.get(pk=pk)
    return render(request,'groups/group_chat_room.html',{'qs':qs})
    

templates/base.html
<!DOCTYPE html>
{% load bootstrap5 %}
{% load i18n %}
{% load custom_tags %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django-chat</title>
    {% include 'links&cdns.html' %}
</head>
<script>
    var navcount=0
  </script>
<body>  
   {% include 'nav.html' %}
   {% block content %}
   {% endblock content %}
  {% comment %} For message notification purposes {% endcomment %}
  <script>
    var userforgroup=`{{request.user.username | remove_unnecessary}}`
    var user=`{{request.user}}`
    const NotificationSocket=new WebSocket(
      'wss://'
      + window.location.host
      + '/ws/'      
      +userforgroup
      +'/'
      +user
      + '/notify/'
  );
    
  
    NotificationSocket.onclose = function(e) {
      console.error('Chat socket closed unexpectedly');
  };
  NotificationSocket.onmessage = function(e) {
    var data = JSON.parse(e.data);        
    $('.navmessagecount').addClass('bg-danger')
    var messagecount=Number($('.navmessagecount').text()) + data.counter
    $('.navmessagecount').text(messagecount)     
    if ($(location).attr('href') == `${location.protocol}//${window.location.host}{% url 'home' %}`){    
      if(data.type == 'Group Notification'){        
        $('.group-section').append(`
        <span class="badge text-bg-success">New!!</span>
        `)
      }
      if (data.reciever_username == `{{request.user}}`){  
        $(`#${data.sender_id}newmessage`).text('New Messages')
        $(`#${data.sender_id}lastchatspan`).text(data.chat)        
    }
    }
    else{      
      $('.navmessagecount').addClass('bg-danger')
      var messagecount=Number($('.navmessagecount').text()) + data.counter
      $('.navmessagecount').text(messagecount)   
      if ($(location).attr('href') == `${location.protocol}//${window.location.host}{% url 'home_groups' %}`){  
          $(`#${data.groupid}groupmessage`).text('New Messages')
          $(`#${data.groupid}lastchat`).text(data.chat)
          if(data.type == 'Personal Notification'){            
            $('.chat-section').append(`
            <span class="badge text-bg-success">New!!</span>
            `)
          }
      }
    }
};
  </script>
</body>
</html>

templates/chat.html
{% extends 'home.html' %}
{% load custom_tags %}
{% block chatblock %}
<script>
  $(document).ready(function() {
    $('.group-section').removeClass('border-top border-start border-success')
    $('.chat-section').addClass('border-top border-end border-success')
  })
</script>
<div class="card MainContent" style="width: 100%;">
    {% for i,k in combined %}
    {% for j in i %}
    <a href="{% url 'chats:create_personal_room' pk=j.id %}" class='btn p-0'>
      {% endfor %}
    <div>  
      
      <span class="px-2 bg-secondary rounded" style='float:left; font-size:1.2rem;'>{{i | get_username}}</span>    
      <span class="px-2 rounded {{i | get_id}}isonline" style=''>{{i | is_online }}</span>    
      <script>
        var online=`{{i | is_online }}`        
        if (online == 'Online'){
          $('.{{i | get_id}}isonline').addClass('bg-success rounded')
        }
        else{
          $('.{{i | get_id}}isonline').text('Last Seen: '+online)
        }
      </script>
      {% if k.chats.last %}
        <span class="bg-danger rounded new_message_count px-2" id='{{i | get_id}}newmessage' style='float:right;'>{{k.chats.last | not_viewed:request.user}}</span>
        {% endif %}
      </div>        
    </a>
    {% if k.chats.last %}
    <ul class="list-group list-group-flush bg-success border-bottom border-5">
      <li class="ms-2 list-group-item mb-2" id='{{i | get_id}}lastchatspan'>{{k.chats.last}}</span></li>        
    </ul>
    {% else %}
    <ul class="list-group list-group-flush bg-success border-bottom border-5">
      <li class="ms-2 list-group-item mb-2" id='{{i | get_id}}lastchatspan'>No Chats Yet</span></li>        
    </ul>
    {% endif %}
      {% empty %}      
      <div class="card-header bg-secondary">
      </div>
      <ul class="list-group list-group-flush bg-success border-bottom border-5">
        <li class="ms-2 list-group-item mb-2">No Chats Yet!!</span></li>        
      </ul>
    {% endfor %}
</div>
{% endblock chatblock %}

templates/groups.html
{% extends 'home.html' %}
{% load custom_tags %}
{% block chatblock %}
{% load bootstrap5 %}
<script>
$(document).ready(function() {
    $('.chat-section').removeClass('border-top border-end border-success')
    $('.group-section').addClass('border-top border-start border-success')
  })
</script>
{% if GroupObj %}
  {% for i in GroupObj %}  
  <div class="card MainContent" style="width: 100%;">
    <a href="{% url 'groups:group_chat_room' pk=i.id %}" class='btn p-0'>
  <div>  
    <span class="px-2 bg-secondary rounded" style='float:left; font-size:1.2rem;'>{{i.RoomName}}</span>        
    </div>        
    <span class="bg-danger rounded new_message_count px-2" id='{{i.id}}groupmessage' style='float:right;'>{{GroupObj | not_in_the_chat:request.user}}</span>
  </a>  
  {% if i.chats.last %}
  <ul class="list-group list-group-flush bg-success border-bottom border-5">
    <li class="ms-2 list-group-item mb-2" id='{{i.id}}lastchat'>{{i.chats.last}}</span></li>        
  </ul>
    {% else %}        
    <ul class="list-group list-group-flush bg-success border-bottom border-5">
      <li class="ms-2 list-group-item mb-2">No Chats Yet!!</span></li>        
    </ul>
    {% endif %}
</div>
{% endfor %}
{% comment %} <i class="bi bi-plus-circle-fill" style='font-size:3rem; color:#ff6f0f'></i> {% endcomment %}
<h1>  
  <i class="bi btn bi-plus-circle-fill btn-outline-secondary bg-gradient" style="position:fixed; bottom:5px; width:100%; z-index:1; background-color:#0c2431" data-bs-toggle="modal" data-bs-target="#GroupModal" data-bs-whatever="@mdo">Click here to add a new group</i> 
</h1>
{% else %}
<div class="container text-center mt-5 reactive-text">
    <h1>
        You are not in any groups yet!<br>
        <i class="bi btn bi-plus-circle btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#GroupModal" data-bs-whatever="@mdo">Click here to add a new group</i> 
    </h1>
</div>


{% comment %} Modal {% endcomment %}
{% endif %}
<div class="modal fade other-components" id="GroupModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add New Group</h5>          
      </div>
      <div class="modal-body">
        <div class="alert alert-warning" role="alert">
          Note: You do not have to select you username in the members field
        </div>
       <form action="{% url 'home_groups' %}" method="post">
        {%bootstrap_form form%}      
        {% csrf_token %}            
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create</button>
      </div>
    </form>
    </div>
  </div>
</div>
{% endblock chatblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="chatandgroups text-center">
<div class="row">
  <div class="col">
    <a href="{% url 'home' %}" style='text-decoration: none;'><div class="chat-section col position-relative">Chats</div></a>
  </div>
  <div class="col">
    <a href="{% url 'home_groups' %}" style='text-decoration: none;'><div class="border-top border-start border-success group-section col position-relative">Groups</div></a>
  </div>
</div>
</div>
<hr style="width:100%", size="3", color=white> 
{% comment %} {% for i in RoomObjects %}
  {{i.chats.last}}
{% endfor %} {% endcomment %}
{% block chatblock %}{% endblock chatblock %}
{% endblock content %}
{% comment %} <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
      <span class="visually-hidden">New alerts</span>
    </span> {% endcomment %}

templates/links&cdns.html
{% load static %}
{% comment %} Icon{% endcomment %}
<link type="image/png" sizes="16x16" rel="icon" href="https://i.ibb.co/DMbj77T/icons8-django-16.png">


{% comment %} Jquery {% endcomment %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

{% comment %} Bootstrap {% endcomment %}
<!-- CSS only -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

{% comment %} Google fonts cdn {% endcomment %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

{% comment %} Fonts for chats{% endcomment %}
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
{% comment %} css rules for font family font-family: 'Source Sans Pro', sans-serif; {% endcomment %}

{% comment %} Fonts for site {% endcomment %}
<link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300&display=swap" rel="stylesheet">
{% comment %} css family rules font-family: 'Fira Code', monospace; {% endcomment %}

{% comment %} Static {% endcomment %}
<script src="{% static 'js/themes.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/master.css' %}">

templates/nav.html
{% load custom_tags %}
<nav class="navbar navbar-expand">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Django-chat</a>
      <button type="button" class="btn other-components border btn-sm position-relative">
        <i class="bi bi-bell"></i>
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger navmessagecount">
         {{request.user | get_counter}}
        </span>
      </button> 
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
        {% include 'snippets/search_form.html' %}
        <div class="nav-item dropdown d-flex">
          <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </a>
          <ul class="dropdown-menu dropdown-menu-end other-components p-3 bg-gradient">
            {% if not user.is_authenticated %}
            <li class="nav-item mb-2">
              <a class="nav-link active" aria-current="page" href="{% url 'account_login' %}">Login</a>
            </li>
            <li class="nav-item mb-2">
              <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
            </li>
            {% else %}
            <li class="nav-item mb-2">
              <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
            <li class="nav-item mb-2">
              <a class="nav-link" href="{% url 'account_change_password' %}">ChangePassword</a>
            </li>
            {% endif %}
            {% if user.is_superuser %}
            <li class="nav-item mb-2">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            {% endif %}
            <li class="nav-item mb-2">
              <button class="other-components border-0 p-0" id='theme-button'>Theme: Light</button>
            </li>
          </ul>
        </div>
       
      </div>
    </div>
  </nav>